import {
  Speed as KpiIcon,
  ShowChart as TrendIcon,
  CompareArrows as CompareIcon,
  PieChart as DistributionIcon,
  Warning as AlertsIcon,
  Timeline as TimelineIcon,
  Notes as NarrativeIcon,
  ViewList as EventLogIcon,
  BarChart as BarIcon,
  Layers as CompositionIcon,
  AccountTree as SankeyIcon,
  GridView as HeatmapIcon,
  Build as DiagnosticIcon,
  HelpOutline as UncertaintyIcon,
  People as PeopleIcon,
  Devices as DeviceIcon,
  Public as GlobeIcon,
  Chat as ChatIcon,
  SmartToy as AgentIcon,
  Lock as VaultIcon,
  Hexagon as HexIcon,
  Hub as NetworkIcon,
  AreaChart as CumulativeIcon,
} from '@mui/icons-material'

export const SCENARIO_ICONS = {
  kpi: KpiIcon,
  trend: TrendIcon,
  'trend-multi-line': TrendIcon,
  'trends-cumulative': CumulativeIcon,
  comparison: CompareIcon,
  distribution: DistributionIcon,
  composition: CompositionIcon,
  'category-bar': BarIcon,
  alerts: AlertsIcon,
  timeline: TimelineIcon,
  eventlogstream: EventLogIcon,
  narrative: NarrativeIcon,
  'flow-sankey': SankeyIcon,
  'matrix-heatmap': HeatmapIcon,
  diagnosticpanel: DiagnosticIcon,
  uncertaintypanel: UncertaintyIcon,
  peopleview: PeopleIcon,
  peoplehexgrid: HexIcon,
  peoplenetwork: NetworkIcon,
  edgedevicepanel: DeviceIcon,
  supplychainglobe: GlobeIcon,
  chatstream: ChatIcon,
  agentsview: AgentIcon,
  vaultview: VaultIcon,
}
