import {
  Box,
  Typography,
  Button,
  Stack,
  CircularProgress,
  Avatar,
  Menu,
  MenuItem,
  alpha,
  useTheme,
} from '@mui/material'
import RefreshIcon from '@mui/icons-material/Refresh'
import DownloadIcon from '@mui/icons-material/Download'
import PsychologyIcon from '@mui/icons-material/Psychology'
import TableChartIcon from '@mui/icons-material/TableChart'
import AssessmentIcon from '@mui/icons-material/Assessment'
import DataObjectIcon from '@mui/icons-material/DataObject'
import LightbulbIcon from '@mui/icons-material/Lightbulb'
import WarningAmberIcon from '@mui/icons-material/WarningAmber'
import TrendingUpIcon from '@mui/icons-material/TrendingUp'
import BarChartIcon from '@mui/icons-material/BarChart'
import AiUsageNotice from '@/components/ai/AiUsageNotice'
import StatCard from './StatCard'
import { neutral } from '@/app/theme'

const EXPORT_FORMATS = ['json', 'excel', 'pdf', 'csv', 'markdown', 'html']

export default function AnalyzeHeader({
  stats,
  analysisResult,
  isExporting,
  exportMenuAnchor,
  onExportClick,
  onExportClose,
  onExport,
  onReset,
}) {
  const theme = useTheme()

  return (
    <Box
      sx={{
        pt: 4,
        pb: analysisResult ? 2 : 4,
        px: 4,
        background: theme.palette.mode === 'dark'
          ? `linear-gradient(135deg, ${alpha(theme.palette.text.primary, 0.06)} 0%, ${alpha(theme.palette.text.primary, 0.03)} 50%, transparent 100%)`
          : `linear-gradient(135deg, ${neutral[100]} 0%, ${neutral[50]} 50%, transparent 100%)`,
        borderBottom: `1px solid ${alpha(theme.palette.divider, 0.1)}`,
      }}
    >
      <Stack direction="row" alignItems="center" justifyContent="space-between">
        <Stack direction="row" alignItems="center" spacing={2}>
          <Avatar
            sx={{
              width: 56,
              height: 56,
              background: theme.palette.mode === 'dark' ? neutral[700] : neutral[900],
              boxShadow: `0 8px 24px ${alpha(theme.palette.common.black, 0.2)}`,
            }}
          >
            <PsychologyIcon sx={{ fontSize: 28 }} />
          </Avatar>
          <Box>
            <Typography
              variant="h5"
              fontWeight={600}
              color="text.primary"
            >
              AI Document Analysis
            </Typography>
            <Typography variant="body2" color="text.secondary" fontWeight={500}>
              Intelligent extraction, analysis, visualization & insights powered by AI
            </Typography>
          </Box>
        </Stack>
        <Stack direction="row" spacing={1.5}>
          {analysisResult && (
            <>
              <Button
                variant="outlined"
                startIcon={isExporting ? <CircularProgress size={16} color="inherit" /> : <DownloadIcon />}
                onClick={onExportClick}
                disabled={isExporting}
                sx={{
                  borderRadius: 1,
                  textTransform: 'none',
                  fontWeight: 600,
                  borderWidth: 2,
                  '&:hover': { borderWidth: 2 },
                }}
              >
                Export
              </Button>
              <Menu
                anchorEl={exportMenuAnchor}
                open={Boolean(exportMenuAnchor)}
                onClose={onExportClose}
                PaperProps={{
                  sx: { borderRadius: 1, minWidth: 140 },
                }}
              >
                {EXPORT_FORMATS.map((fmt) => (
                  <MenuItem key={fmt} onClick={() => onExport(fmt)}>
                    {fmt.toUpperCase()}
                  </MenuItem>
                ))}
              </Menu>
              <Button
                variant="contained"
                startIcon={<RefreshIcon />}
                onClick={onReset}
                sx={{
                  borderRadius: 1,
                  textTransform: 'none',
                  fontWeight: 600,
                  background: theme.palette.mode === 'dark' ? neutral[700] : neutral[900],
                  boxShadow: `0 4px 14px ${alpha(theme.palette.common.black, 0.2)}`,
                  '&:hover': {
                    background: theme.palette.mode === 'dark' ? neutral[500] : neutral[700],
                  },
                }}
              >
                New Analysis
              </Button>
            </>
          )}
        </Stack>
      </Stack>

      <Box sx={{ mt: 3 }}>
        <AiUsageNotice
          title="AI analysis"
          description="Uses the document you upload. Results are generated by AI; review before sharing."
          chips={[
            { label: 'Source: Uploaded document', color: 'default', variant: 'outlined' },
            { label: 'Confidence: Review required', color: 'warning', variant: 'outlined' },
            { label: 'Reversible: No source changes', color: 'success', variant: 'outlined' },
          ]}
          dense
        />
      </Box>

      {/* Stats Bar */}
      {stats && (
        <Stack direction="row" spacing={2} sx={{ mt: 3, flexWrap: 'wrap' }} useFlexGap>
          <StatCard icon={<TableChartIcon />} label="Tables" value={stats.tables} delay={0} />
          <StatCard icon={<AssessmentIcon />} label="Metrics" value={stats.metrics} delay={1} />
          <StatCard icon={<DataObjectIcon />} label="Entities" value={stats.entities} delay={2} />
          <StatCard icon={<LightbulbIcon />} label="Insights" value={stats.insights} delay={3} />
          <StatCard icon={<WarningAmberIcon />} label="Risks" value={stats.risks} delay={4} />
          <StatCard icon={<TrendingUpIcon />} label="Opportunities" value={stats.opportunities} delay={5} />
          <StatCard icon={<BarChartIcon />} label="Charts" value={stats.charts} delay={6} />
        </Stack>
      )}
    </Box>
  )
}
