export const FORMULA_FUNCTIONS = [
  { name: 'SUM', syntax: 'SUM(range)', description: 'Sum of values' },
  { name: 'AVERAGE', syntax: 'AVERAGE(range)', description: 'Average of values' },
  { name: 'COUNT', syntax: 'COUNT(range)', description: 'Count of numbers' },
  { name: 'COUNTA', syntax: 'COUNTA(range)', description: 'Count of non-empty cells' },
  { name: 'MAX', syntax: 'MAX(range)', description: 'Maximum value' },
  { name: 'MIN', syntax: 'MIN(range)', description: 'Minimum value' },
  { name: 'IF', syntax: 'IF(condition, true_val, false_val)', description: 'Conditional logic' },
  { name: 'VLOOKUP', syntax: 'VLOOKUP(value, range, col, exact)', description: 'Vertical lookup' },
  { name: 'HLOOKUP', syntax: 'HLOOKUP(value, range, row, exact)', description: 'Horizontal lookup' },
  { name: 'SUMIF', syntax: 'SUMIF(range, criteria, sum_range)', description: 'Conditional sum' },
  { name: 'COUNTIF', syntax: 'COUNTIF(range, criteria)', description: 'Conditional count' },
  { name: 'CONCATENATE', syntax: 'CONCATENATE(text1, text2, ...)', description: 'Join text' },
  { name: 'LEFT', syntax: 'LEFT(text, num_chars)', description: 'Left characters' },
  { name: 'RIGHT', syntax: 'RIGHT(text, num_chars)', description: 'Right characters' },
  { name: 'MID', syntax: 'MID(text, start, length)', description: 'Middle characters' },
  { name: 'LEN', syntax: 'LEN(text)', description: 'Text length' },
  { name: 'TRIM', syntax: 'TRIM(text)', description: 'Remove extra spaces' },
  { name: 'ROUND', syntax: 'ROUND(number, decimals)', description: 'Round number' },
  { name: 'ABS', syntax: 'ABS(number)', description: 'Absolute value' },
  { name: 'TODAY', syntax: 'TODAY()', description: 'Current date' },
  { name: 'NOW', syntax: 'NOW()', description: 'Current date and time' },
  { name: 'YEAR', syntax: 'YEAR(date)', description: 'Year from date' },
  { name: 'MONTH', syntax: 'MONTH(date)', description: 'Month from date' },
  { name: 'DAY', syntax: 'DAY(date)', description: 'Day from date' },
]
